# Use root/example as user/password credentials
version: '3.1'

services:

    web:
        build: .
        command: python -m flask run -h 0.0.0.0
        environment:
            - DB_HOST=db
            - FLASK_APP=postbook
            - FLASK_ENV=production
        ports:
            - 5000:5000
        volumes:
            - .:/code
        depends_on:
            - db

    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: postbook
            MYSQL_DATABASE: postbook
            MYSQL_USER: postbook
            MYSQL_PASSWORD: postbook
        ports:
            - 3306:3306

    adminer:
        image: adminer
        ports:
            - 8080:8080

